version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exerciseDatabase

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db:
    driver: local