version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exerciseDatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db:
    driver: local